starting process...

2023-02-28 19:47:06.457624 - starting process...
2023-02-28 19:56:15.869580 - starting process...
2023-02-28 20:04:00.152328 - starting process...
2023-02-28 20:05:02.300198 - Err4: <class 'AttributeError'>; 'tuple' object has no attribute 'number_format'; ('tuple' object has no attribute 'number_format'), line: 422, in app.py | UTC: 2023-02-28 20:05:02.300198
2023-02-28 20:11:08.899887 - starting process...
2023-02-28 20:12:04.094541 - Err4: <class 'AttributeError'>; 'tuple' object has no attribute 'number_format'; ('tuple' object has no attribute 'number_format'), line: 422, in app.py | UTC: 2023-02-28 20:12:04.094541
2023-02-28 20:12:23.603110 - starting process...
2023-02-28 21:21:26.763077 - starting process...
2023-02-28 21:22:02.506487 - Err4: <class 'IndexError'>; list index out of range; (list index out of range), line: 352, in app.py | UTC: 2023-02-28 21:22:02.506487
2023-02-28 21:23:13.352575 - starting process...
2023-02-28 21:25:14.763982 - starting process...
